name: CI

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  quality:
    name: Lint, Types, Tests (Node ${{ matrix.node }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [18, 20]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: yarn

      - name: Install deps
        run: |
          corepack enable || true
          yarn install --prefer-offline

      - name: Lint
        run: yarn lint

      - name: Format check
        run: yarn format:check

      - name: Typecheck
        run: yarn typecheck

      - name: Tests
        env:
          CI: true
        run: yarn test

